/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        // Legacy (keep for existing code compatibility) - updated to Paper palette
        midnight: { DEFAULT: '#FAFAF8', 50: '#FFFFFF', 100: '#F5F5F0', 200: '#E5E7EB', 800: '#374151', 900: '#111827' },
        cream: { DEFAULT: '#FFFFFF', 100: '#FAFAF8', 200: '#F5F5F0' },
        gold: { DEFAULT: '#D97706', light: '#FEF3C7', dark: '#92400E' },
        emerald: { DEFAULT: '#16A34A', light: '#DCFCE7', dark: '#15803D' },
        coral: { DEFAULT: '#DC2626', light: '#FEE2E2', dark: '#991B1B' },
        steel: { DEFAULT: '#6B7280', light: '#F3F4F6', dark: '#374151' },

        // Paper design system
        brand: {
          navy: '#111827',
          'navy-light': '#374151',
          'navy-dark': '#1F2937',
          blue: '#8B5CF6',
          'blue-light': '#A78BFA',
          'blue-dark': '#7C3AED',
          teal: '#06B6D4',
          'teal-light': '#67E8F9',
        },
        outcome: {
          win: '#16A34A',
          'win-bg': '#F0FDF4',
          'win-border': '#BBFF10',
          loss: '#DC2626',
          'loss-bg': '#FEF2F2',
          'loss-border': '#FEE2E2',
          mixed: '#D97706',
          'mixed-bg': '#FFFBEB',
          'mixed-border': '#FEF08A',
          neutral: '#6B7280',
          'neutral-bg': '#F9FAFB',
          'neutral-border': '#E5E7EB',
        },
        surface: {
          base: '#FAFAF8',
          card: '#FFFFFF',
          border: '#E5E7EB',
          'border-strong': '#D1D5DB',
          overlay: 'rgba(17,24,39,0.6)',
        },
        text: {
          primary: '#111827',
          secondary: '#374151',
          muted: '#6B7280',
          inverse: '#FFFFFF',
          link: '#111111',
        },
      },
      fontFamily: {
        display: ['Montserrat', 'system-ui', 'sans-serif'],
        body: ['Roboto', 'system-ui', 'sans-serif'],
        data: ['PT Mono', 'monospace'],
        mono: ['PT Mono', 'monospace'],
      },
      fontSize: {
        'display-2xl': ['4.5rem', { lineHeight: '1.05', letterSpacing: '-0.03em' }],
        'display-xl': ['3.75rem', { lineHeight: '1.08', letterSpacing: '-0.02em' }],
        'display-lg': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.02em' }],
        'display-md': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.01em' }],
        'display-sm': ['1.875rem', { lineHeight: '1.2' }],
        'label-lg': ['0.875rem', { lineHeight: '1.4', letterSpacing: '0.07em' }],
        'label-sm': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.09em' }],
        'data-lg': ['2rem', { lineHeight: '1', letterSpacing: '-0.02em' }],
        'data-sm': ['1.25rem', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.06), 0 1px 2px rgba(0,0,0,0.04)',
        'card-hover': '0 4px 16px rgba(0,0,0,0.10), 0 2px 4px rgba(0,0,0,0.06)',
        'card-elevated': '0 12px 32px rgba(0,0,0,0.13), 0 4px 8px rgba(0,0,0,0.06)',
        'glow-blue': '0 0 24px rgba(64,64,242,0.28)',
        'glow-teal': '0 0 24px rgba(13,148,136,0.28)',
        'inner-sm': 'inset 0 1px 2px rgba(0,0,0,0.06)',
      },
      borderRadius: {
        card: '14px',
        'card-sm': '10px',
        badge: '6px',
        pill: '9999px',
      },
      animation: {
        // Legacy
        'fade-in': 'fadeIn 0.6s ease forwards',
        'slide-up': 'slideUp 0.8s cubic-bezier(0.16,1,0.3,1) forwards',
        'draw': 'draw 1.5s cubic-bezier(0.16,1,0.3,1) forwards',
        'count': 'countUp 0.4s ease forwards',
        'glow-pulse': 'glowPulse 3s ease infinite',
        'bar-fill': 'barFill 1.2s cubic-bezier(0.16,1,0.3,1) forwards',
        // New
        'fade-up': 'fadeUp 0.45s ease-out forwards',
        'scale-in': 'scaleIn 0.25s ease-out forwards',
        'slide-in-right': 'slideInRight 0.35s cubic-bezier(0.32,0.72,0,1) forwards',
        'slide-in-left': 'slideInLeft 0.35s cubic-bezier(0.32,0.72,0,1) forwards',
        shimmer: 'shimmer 1.8s infinite linear',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'marquee': 'marquee 60s linear infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(32px)' }, to: { opacity: '1', transform: 'none' } },
        draw: { from: { strokeDashoffset: 'var(--circumference)' }, to: { strokeDashoffset: 'var(--offset)' } },
        countUp: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'none' } },
        glowPulse: { '0%,100%': { boxShadow: '0 0 20px rgba(64,64,242,0.08)' }, '50%': { boxShadow: '0 0 40px rgba(64,64,242,0.16)' } },
        barFill: { from: { width: '0%' }, to: { width: 'var(--target-width)' } },
        fadeUp: { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        slideInRight: { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        slideInLeft: { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
        shimmer: { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        pulseSoft: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
      },
    },
  },
  plugins: [],
};
