/** @type {import('tailwindcss').Config} */
module.exports = {
  content: [
    "./app/**/*.{js,ts,jsx,tsx}",
    "./components/**/*.{js,ts,jsx,tsx}",
  ],
  // LEXISNEXIS-INSPIRED DESIGN SYSTEM — Light corporate
  theme: {
    extend: {
      colors: {
        // LexisNexis-inspired palette
        midnight: { DEFAULT: '#00172E', 50: '#001A35', 100: '#00203F', 200: '#002A4F', 800: '#FAFBFC', 900: '#FFFFFF' },
        cream: { DEFAULT: '#EDEEEE', 100: '#F5F6F7', 200: '#FAFBFC' },
        gold: { DEFAULT: '#B86E00', light: 'rgba(184,110,0,0.08)', dark: '#8B5500' },
        emerald: { DEFAULT: '#07874A', light: 'rgba(7,135,74,0.08)', dark: '#056B3B' },
        coral: { DEFAULT: '#CC1019', light: 'rgba(204,16,25,0.08)', dark: '#990C13' },
        steel: { DEFAULT: '#666666', light: '#E5EBF0', dark: '#455A64' },

        // LexisNexis brand
        brand: {
          navy: '#00172E',
          'navy-light': '#001A35',
          'navy-dark': '#000F1F',
          red: '#E8171F',
          'red-light': '#FF2B33',
          'red-dark': '#CC1019',
          teal: '#006997',
          'teal-light': '#0080B8',
          'teal-dark': '#005A82',
        },
        outcome: {
          win: '#07874A',
          'win-bg': 'rgba(7,135,74,0.08)',
          'win-border': 'rgba(7,135,74,0.25)',
          loss: '#CC1019',
          'loss-bg': 'rgba(204,16,25,0.08)',
          'loss-border': 'rgba(204,16,25,0.25)',
          mixed: '#B86E00',
          'mixed-bg': 'rgba(184,110,0,0.08)',
          'mixed-border': 'rgba(184,110,0,0.25)',
          neutral: '#666666',
          'neutral-bg': '#F5F6F7',
          'neutral-border': '#D5D8DC',
        },
        surface: {
          base: '#EDEEEE',
          card: '#FFFFFF',
          border: '#D5D8DC',
          'border-strong': '#455A64',
          overlay: 'rgba(0,23,46,0.60)',
        },
        text: {
          primary: '#212529',
          secondary: '#455A64',
          muted: '#666666',
          inverse: '#FAFBFC',
          link: '#006997',
        },
      },
      fontFamily: {
        display: ['Lato', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        body: ['Lato', 'Helvetica Neue', 'Helvetica', 'Arial', 'sans-serif'],
        data: ['JetBrains Mono', 'Menlo', 'monospace'],
        mono: ['JetBrains Mono', 'Menlo', 'monospace'],
      },
      fontSize: {
        'display-2xl': ['4.5rem', { lineHeight: '1.05', letterSpacing: '-0.02em' }],
        'display-xl': ['3.75rem', { lineHeight: '1.08', letterSpacing: '-0.02em' }],
        'display-lg': ['3rem', { lineHeight: '1.1', letterSpacing: '-0.01em' }],
        'display-md': ['2.25rem', { lineHeight: '1.15', letterSpacing: '-0.01em' }],
        'display-sm': ['1.875rem', { lineHeight: '1.2' }],
        'label-lg': ['0.875rem', { lineHeight: '1.4', letterSpacing: '0.07em' }],
        'label-sm': ['0.75rem', { lineHeight: '1.4', letterSpacing: '0.09em' }],
        'data-lg': ['2rem', { lineHeight: '1', letterSpacing: '-0.02em' }],
        'data-sm': ['1.25rem', { lineHeight: '1.2', letterSpacing: '-0.01em' }],
      },
      boxShadow: {
        card: '0 1px 3px rgba(0,0,0,0.08)',
        'card-hover': '0 4px 16px rgba(0,0,0,0.12), 0 1px 3px rgba(0,0,0,0.06)',
        'card-elevated': '0 8px 24px rgba(0,0,0,0.12), 0 2px 6px rgba(0,0,0,0.06)',
        'glow-red': '0 2px 12px rgba(232,23,31,0.15)',
        'glow-teal': '0 2px 12px rgba(0,105,151,0.15)',
        'inner-sm': 'inset 0 1px 2px rgba(0,0,0,0.06)',
        glass: '0 1px 3px rgba(0,0,0,0.08)',
        accent: '0 2px 8px rgba(232,23,31,0.15)',
        'accent-lg': '0 4px 16px rgba(232,23,31,0.20)',
      },
      borderRadius: {
        card: '4px',
        'card-sm': '3px',
        badge: '3px',
        pill: '9999px',
      },
      animation: {
        'fade-in': 'fadeIn 0.6s ease forwards',
        'slide-up': 'slideUp 0.6s ease forwards',
        'draw': 'draw 1.5s ease forwards',
        'count': 'countUp 0.4s ease forwards',
        'glow-pulse': 'glowPulse 3s ease infinite',
        'bar-fill': 'barFill 1.2s ease forwards',
        'fade-up': 'fadeUp 0.45s ease-out forwards',
        'scale-in': 'scaleIn 0.25s ease-out forwards',
        'slide-in-right': 'slideInRight 0.35s ease forwards',
        'slide-in-left': 'slideInLeft 0.35s ease forwards',
        shimmer: 'shimmer 1.8s infinite linear',
        'pulse-soft': 'pulseSoft 2s ease-in-out infinite',
        'marquee': 'marquee 60s linear infinite',
      },
      keyframes: {
        fadeIn: { from: { opacity: '0' }, to: { opacity: '1' } },
        slideUp: { from: { opacity: '0', transform: 'translateY(24px)' }, to: { opacity: '1', transform: 'none' } },
        draw: { from: { strokeDashoffset: 'var(--circumference)' }, to: { strokeDashoffset: 'var(--offset)' } },
        countUp: { from: { opacity: '0', transform: 'translateY(8px)' }, to: { opacity: '1', transform: 'none' } },
        glowPulse: { '0%,100%': { boxShadow: '0 0 8px rgba(0,105,151,0.05)' }, '50%': { boxShadow: '0 0 16px rgba(0,105,151,0.12)' } },
        barFill: { from: { width: '0%' }, to: { width: 'var(--target-width)' } },
        fadeUp: { from: { opacity: '0', transform: 'translateY(20px)' }, to: { opacity: '1', transform: 'translateY(0)' } },
        scaleIn: { from: { opacity: '0', transform: 'scale(0.95)' }, to: { opacity: '1', transform: 'scale(1)' } },
        slideInRight: { from: { transform: 'translateX(100%)' }, to: { transform: 'translateX(0)' } },
        slideInLeft: { from: { transform: 'translateX(-100%)' }, to: { transform: 'translateX(0)' } },
        shimmer: { from: { backgroundPosition: '-200% 0' }, to: { backgroundPosition: '200% 0' } },
        pulseSoft: { '0%,100%': { opacity: '1' }, '50%': { opacity: '0.6' } },
        marquee: { from: { transform: 'translateX(0)' }, to: { transform: 'translateX(-50%)' } },
      },
    },
  },
  plugins: [],
};
